services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: postgres
    container_name: 'db'
    restart: always
    shm_size: 128mb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - "pizzaNetwork"

  meal:
    container_name: meal-service
    image: pizzeria-meal:latest
    build:
      context: .
      dockerfile: meal/Dockerfile
    ports:
      - "9011:9010"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-javaagent:/usr/local/newrelic/newrelic.jar
      - NEW_RELIC_APP_NAME=meal-service  # Change this to the name you want in New Relic
    #    volumes:
    #      - ./newrelic:/usr/local/newrelic
    depends_on:
      - db
    networks:
      - "pizzaNetwork"

  gateway:
    container_name: gateway-service
    image: pizzeria-brandenburg:latest
    build:
      context: .
      dockerfile: brandenburg/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/usr/local/newrelic/newrelic.jar
      - NEW_RELIC_APP_NAME=gateway-service  # Change this to the name you want in New Relic
    #    volumes:
    #      - ./newrelic:/usr/local/newrelic
    depends_on:
      - meal
      - order
      - mail
    networks:
      - "pizzaNetwork"

  order:
    container_name: order-service
    image: pizzeria-order:latest
    build:
      context: .
      dockerfile: order/Dockerfile
    ports:
      - "9091:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-javaagent:/usr/local/newrelic/newrelic.jar
      - NEW_RELIC_APP_NAME=order-service  # Change this to the name you want in New Relic
    #    volumes:
    #      - ./newrelic:/usr/local/newrelic
    depends_on:
      - db
      - mail
      - meal
    networks:
      - "pizzaNetwork"

  mail:
    container_name: mail-service
    image: pizzeria-mail:latest
    build:
      context: .
      dockerfile: mail/Dockerfile
    ports:
      - "8091:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=secret
      - JAVA_TOOL_OPTIONS=-javaagent:/usr/local/newrelic/newrelic.jar
      - NEW_RELIC_APP_NAME=mail-service  # Change this to the name you want in New Relic
    #    volumes:
    #      - ./newrelic:/usr/local/newrelic
    depends_on:
      - meal
    networks:
      - "pizzaNetwork"

  rabbitmq:
    image: rabbitmq:4.0.7
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - "pizzaNetwork"

  agent:
    container_name: newrelic-infra
    build:
      context: .
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    networks:
      - pizzaNetwork

networks:
  pizzaNetwork:
    driver: "bridge"